### PR TITLE
Trying out new things. thank you.

### PR DESCRIPTION
**Pull request by getlowu2**
zkiram teach me revert in git command.

### CODE REVIEW

**Comment by getlowu2** [comment]
why cant i merge?

**Comment by azikram** [comment]
> why cant i merge?

what're you trying to do?

**Comment by getlowu2** [comment]
It's showing me that i can't merge unless the commit is reviewed by
someone.

>

**Review by azikram — APPROVED** [review]

**Comment by azikram** [comment]
> It's showing me that i can't merge unless the commit is reviewed by someone.
reviewed.

**Comment by Shahriar10k** [comment]
**Reviewed** and Merged @getlowu2 #7

**Pull request merged**
